version: '3'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/app
    environment:
     - SECRET_KEY=<SECRET_KEY>
     - ALLOWED_HOSTS=<ALLOWED_HOSTS>
     - DATABASE_URL=<DATABASE_URL>
  db:
    image: postgres:latest
    environment:
     - POSTGRES_USER=<POSTGRES_USER>
     - POSTGRES_PASSWORD=<POSTGRES_PASSWORD>
     - POSTGRES_DB=<POSTGRES_DB>
